Repository RadioPeeker/Radios, pull requests merged in 2020-11, with the labels that each got.

#1 Hrvy.pw radio.json
  radios/H/hrvy/radio.json
Labels: pending

#5 Added Symphony
  radios/S/symphonyradio/radio.json
Labels: pending

#8 Update logo TSR
  radios/T/truckstopradio/radio.json
Labels: modification

#9 Added HitRadio
  radios/H/HitRadio/radio.json
Labels: accepted

#11 fix things
  radios/H/HitRadio/radio.json
Labels: accepted, modification

#12 colour changed
  radios/H/HitRadio/radio.json
Labels: accepted, modification

#13 Removed Pulse
  radios/P/pulse/radio.json
Labels: removal

#16 Updated: Logo Link and website link
  radios/S/symphonyradio/radio.json
Labels: modification

#17 Remove Triple
  radios/T/triple/radio.json
Labels: removal
